--- #YAML:1.0
name: Wx::WidgetMaker
version: 0.10
license: perl
distribution_type: module
requires:
  Wx: 0.13
  perl: 5.6.1
recommends: {}
build_requires: {}
conflicts: {}
provides: {}
generated_by: Module::Build version 0.21
