--- #YAML:1.0
name: Wx-WidgetMaker
version: 0.11
author: Scott Lanning <lannings@who.int>
abstract: a CGI.pm-like library for wxPerl
license: perl
requires:
  Wx: 0.13
  perl: 5.6.1
recommends:
  Module::Build: 0.25
build_requires:
  Test::More: 0
provides:
  Wx::WidgetMaker:
    file: lib/Wx/WidgetMaker.pm
    version: 0.11
generated_by: Module::Build version 0.25
